-- +goose Up
-- +goose StatementBegin
CREATE TABLE "note"
(
    "id"                 bigint      GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 MINVALUE 0 START 0),
    "address"            bytea       NOT NULL,
    "type"               TEXT        NOT NULL,
    "created_at"         timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT "pkey" PRIMARY KEY ("id")
);
-- +goose StatementEnd


-- +goose Down
-- +goose StatementBegin
DROP TABLE "note";
-- +goose StatementEnd