version: "3"

services:
  devcontainer:
    container_name: devcontainer
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - SYS_PTRACE
    command: sleep infinity
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - default
    ports:
      - "8080:8080"
      - "5432:5432"
    volumes:
      - "postgres:/postgres/postgres-data"
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
volumes:
  postgres:
  redis:
networks:
  default:
